### ISSUE TITLE
Support Batch Document Addition 

### ISSUE THREAD

**Issue by NotAmaan** [kestra-io/plugin-meilisearch#8]
### Feature description

Hi, and thank you for creating such a useful plugin! It’s been a great help in connecting Kestra with Meilisearch, and I really appreciate the effort that went into it.

I’m not a Java developer, so correct me if I’m wrong, but the Meilisearch Java client does seem to support adding multiple documents at once. The current implementation, which adds one document at a time, can be quite slow for large datasets.

It would be great if the plugin could take advantage of batching to improve performance.

Thanks again for all your hard work!

**Comment by fdelbrayelle** [comment]
This will be released in a few moments in [plugin-meilisearch v1.4.0](https://github.com/kestra-io/plugin-meilisearch/releases/tag/v1.4.0), thanks @qdequele!

**Comment by Pradumnasaraf** [comment]
Working now. QA done ✅. CC @NotAmaan. Sample code for docs @aj-emerich if you need to add further!

```yaml
id: meilisearch_batch_insert
namespace: integrations.meilisearch

tasks:
  - id: add_documents
    type: io.kestra.plugin.meilisearch.DocumentAdd
    index: "movies_batched"
    url: "http://meilisearch-qa:7700"
    key: "masterKey123"
    batchSize: 4
    from:
      - {id: 1, title: "The Shawshank Redemption", year: 1994}
      - {id: 2, title: "The Godfather", year: 1972}
      - {id: 3, title: "The Dark Knight", year: 2008}
      - {id: 4, title: "Pulp Fiction", year: 1994}
      - {id: 5, title: "Forrest Gump", year: 1994}
      - {id: 6, title: "Inception", year: 2010}
      - {id: 7, title: "Fight Club", year: 1999}
      - {id: 8, title: "The Matrix", year: 1999}
      - {id: 9, title: "Interstellar", year: 2014}
      - {id: 10, title: "Parasite", year: 2019}

  - id: log_add_outputs
    type: io.kestra.plugin.core.log.Log
    message: "documentsAdded={{ outputs.add_documents.documentsAdded }} | taskUids count={{ outputs.add_documents.taskUids | length }} | taskUids={{ outputs.add_documents.taskUids }}"

  - id: search_all
    type: io.kestra.plugin.meilisearch.Search
    index: "movies_batched"
    url: "http://meilisearch-qa:7700"
    key: "masterKey123"
    query: ""

  - id: log_search_hits
    type: io.kestra.plugin.core.log.Log
    message: "totalHits={{ outputs.search_all.totalHits }}"
```

<img width="1278" height="1080" alt="Image" src="https://github.com/user-attachments/assets/da81381f-4aa3-4d77-8edc-f5eab2c1c0e5" />
